// <auto-generated />
namespace PayrollProject.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class NewCreateone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewCreateone));
        
        string IMigrationMetadata.Id
        {
            get { return "201709130453218_NewCreateone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
